; SPDX-License-Identifier: AGPL-3.0-or-later
; SPDX-FileCopyrightText: Fabian Zimber / shiftbloom studio
; Westernis cloud image: PHP overrides on top of docker/mediawiki/zz-wiki.ini (docs/cloudflare-design.md 2.8).
; Uploads: Cloudflare's request body cap is 100 MB on Free/Pro zones ($wgMaxUploadSize = 95 MB).
upload_max_filesize = 95M
post_max_size = 100M
; The code never changes inside a running container
opcache.validate_timestamps = 0
